version: '3'

services:
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    user: "${UID}:${GID}"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db